CREATE TABLE `users_tb` (
`buwana_id` int(11) NOT NULL AUTO_INCREMENT,
`open_id` varchar(255) DEFAULT NULL,
`username` varchar(255) DEFAULT NULL,
`first_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
`last_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
`full_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
`email` varchar(100) DEFAULT NULL,
`password_hash` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
`account_status` varchar(100) DEFAULT NULL,
`created_at` datetime DEFAULT NULL,
`last_login` datetime DEFAULT NULL,
`signup_timetaken` int(10) unsigned DEFAULT NULL,
`honeypotted` tinyint(1) DEFAULT NULL,
`js_enabled_catch` tinyint(1) DEFAULT NULL COMMENT '1 if JS was enabled during signup, 0 if not',
`bot_score` tinyint(3) unsigned DEFAULT NULL,
`role` varchar(255) NOT NULL DEFAULT 'user',
`failed_login_attemptsXXX` int(11) DEFAULT 0,
`password_reset_token` varchar(255) DEFAULT NULL,
`password_reset_expires` datetime DEFAULT NULL,
`password_last_reset_dt` datetime DEFAULT NULL,
`is_two_factor_enabled` tinyint(1) NOT NULL DEFAULT 0,
`brikcoin_balance` decimal(10,5) NOT NULL DEFAULT 0.00000,
`gea_status` varchar(255) NOT NULL DEFAULT 'null',
`terms_of_service` tinyint(1) NOT NULL DEFAULT 0,
`notes` text NOT NULL DEFAULT 'null',
`flagged` tinyint(1) NOT NULL DEFAULT 0,
`suspended` tinyint(1) NOT NULL DEFAULT 0,
`validation_credits` int(11) NOT NULL DEFAULT 3,
`profile_pic` varchar(255) NOT NULL DEFAULT 'null',
`country_id` int(11) DEFAULT NULL,
`language_id` varchar(11) DEFAULT 'en',
`earthen_newsletter_join` tinyint(1) DEFAULT 1,
`legacy_unactivated` tinyint(1) NOT NULL DEFAULT 0,
`login_count` smallint(6) NOT NULL DEFAULT 0,
`birth_date` date DEFAULT NULL,
`deleteable` tinyint(1) NOT NULL DEFAULT 1,
`watershed_id` int(11) DEFAULT NULL,
`continent_code` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
`location_full` varchar(254) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
`location_watershed` varchar(254) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
`location_lat` decimal(10,8) DEFAULT NULL,
`location_long` decimal(11,8) DEFAULT NULL,
`community_id` int(11) DEFAULT NULL,
`connected_app_ids` text DEFAULT NULL,
`earthling_emoji` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
`time_zone` varchar(50) NOT NULL DEFAULT 'Etc/GMT',
`test_sent` tinyint(1) NOT NULL DEFAULT 0,
`test_sent_date_time` datetime DEFAULT NULL,
`validated` tinyint(1) NOT NULL DEFAULT 0,
`processing` tinyint(1) DEFAULT NULL,
PRIMARY KEY (`buwana_id`),
UNIQUE KEY `username` (`username`),
UNIQUE KEY `open_id` (`open_id`) USING BTREE,
KEY `users_tb_fk20` (`country_id`),
KEY `users_tb_fk22` (`language_id`),
KEY `idx_users_buwana_id` (`buwana_id`),
KEY `fk_user_watershed` (`watershed_id`),
KEY `fk_user_continent` (`continent_code`),
KEY `fk_users_community` (`community_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5205 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci